In [1]:
#1. Import the numpy package under the name
import numpy as np

In [2]:
#2. Print the numpy version and the configuration
print(np.__version__)
np.show_config()

1.18.5
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/opt/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/opt/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/opt/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/opt/anaconda3/include']


In [3]:
#3. Create a null vector of size 10
v = np.zeros(10)
print (v)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
#4. How to find the memory size of any array

A = np.ones((4,4))
#A.size - кол-во элементов в массиве, А.itemsize- размер одного элемента
print(A.size * A.itemsize, 'байт')



128 байт


In [5]:
#5. How to get the documentation of the numpy add function from the command line? 

#  python3 -c "import numpy; numpy.info(numpy.add)"

In [6]:
#6. Create a null vector of size 10 but the fifth value which is 1 
v = np.zeros(10)
v[4] = 1
print(v)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [7]:
#7. Create a vector with values ranging from 10 to 49 
v = np.arange(10,50)
print(v)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [34]:
#8. Reverse a vector (first element becomes last)
v = np.arange(50)
v = v[::-1]
print(v)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [9]:
#9. Create a 3x3 matrix with values ranging from 0 to 8
A = np.arange(9).reshape(3,3)
print(A)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [10]:
#10. Find indices of non-zero elements from [1,2,0,0,4,0]
x = np.nonzero([1,2,0,0,4,0])
print(x)

(array([0, 1, 4]),)


In [11]:
#11. Create a 3x3 identity matrix
E = np.eye(3)
print(E)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
#12. Create a 3x3x3 array with random values
A = np.random.random((3,3,3))
print(A)

[[[0.63180887 0.74696238 0.26958055]
  [0.13233397 0.56570585 0.12011979]
  [0.80688179 0.67587754 0.38010936]]

 [[0.27481769 0.42077688 0.99530772]
  [0.42415199 0.03520686 0.77840577]
  [0.79628098 0.07844715 0.52565086]]

 [[0.33303326 0.31593078 0.6540195 ]
  [0.06288815 0.20285917 0.26342396]
  [0.38384    0.15096342 0.5009635 ]]]


In [35]:
#13. Create a 10x10 array with random values and find the minimum and maximum values
A = np.random.random((10,10))

A_min = A.min()
A_max = A.max()
print(A_min, A_max)

0.01832350240258629 0.9852345446226882


In [36]:
#14. Create a random vector of size 30 and find the mean value
v = np.random.random(30)
v_mean = v.mean()
print(v_mean)

0.4810887632421411


In [15]:
#15. Create a 2d array with 1 on the border and 0 inside
A = np.ones((15,15))
A[1:-1,1:-1] = 0
print(A)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [47]:
#16. How to add a border (filled with 0's) around an existing array?
A = np.ones((9,10))
print(A)

print()

A = np.pad(A, pad_width=1, mode='constant', constant_values=0)
print(A)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [17]:
#17. What is the result of the following expression?

print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


In [18]:
#18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal 
Z = np.diag(np.arange(1, 5),-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [19]:
#19. Create a 8x8 matrix and fill it with a checkerboard pattern 

A = np.zeros((8,8))
A[1::2,::2] = 1
A[::2,1::2] = 1
print(A)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [20]:
#20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


In [21]:
#21. Create a checkerboard 8x8 matrix using the tile function 
A = np.tile(np.array([[0,1],[1,0]]), (4,4))
print(A)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [50]:
#22. Normalize a 5x5 random matrix 
A = np.random.random((5,5))

A_min = A.min()
A_max = A.max()
A_norm = (A - A_min)/(A_max - A_min)

print(A_norm)

After normalization:
[[0.67771654 0.61445531 0.21302709 0.15319926 0.11133605]
 [0.19857391 0.6191976  0.         0.95338939 0.28564213]
 [0.82553552 0.19622749 0.81289775 0.35743604 1.        ]
 [0.47545465 0.34185583 0.87486396 0.62407828 0.91779735]
 [0.29901942 0.13907721 0.46388041 0.3013445  0.39969506]]


In [53]:
#23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) 

color = np.dtype([("R", np.ubyte, 1),

("G", np.ubyte, 1),

("B", np.ubyte, 1),

("A", np.ubyte, 1)])


<ipython-input-53-ddc59ba14983>:3: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color = np.dtype([("R", np.ubyte, 1),


In [24]:
#24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) 
A1 = np.ones((5,3))
A2 = np.ones((3,2))

A = np.dot(A1, A2)

print(A)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [52]:
#25. Given a 1D array, negate all elements which are between 3 and 8, in place.
v = np.arange(11)
v[(3 < v) & (v <= 8)] *= -1
print(v)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [54]:
#26. What is the output of the following script?
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [57]:
#27. Consider an integer vector Z, which of these expressions are legal? 
Z = np.arange(5)
print (Z)

print()

print (Z**Z)
print (2 << Z >> 2)
print (Z <- Z)
print (1j*Z)
print (Z/1/1)
# недопутисмо (Z<Z>Z)


[0 1 2 3 4]

[  1   1   4  27 256]
[0 1 2 4 8]
[False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j]
[0. 1. 2. 3. 4.]


In [58]:
#28. What are the result of the following expressions?
print (np.array(0) / np.array(0))
print (np.array(0) // np.array(0))
print (np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


<ipython-input-58-2f7dc9a1534e>:2: RuntimeWarning: invalid value encountered in true_divide
  print (np.array(0) / np.array(0))
<ipython-input-58-2f7dc9a1534e>:3: RuntimeWarning: divide by zero encountered in floor_divide
  print (np.array(0) // np.array(0))


In [61]:
#29. How to round away from zero a float array ?
A = np.random.uniform(-10,+10,10)
print(A)
print()
print (np.copysign(np.ceil(np.abs(A)), A))

[-8.84966193  0.41307673  4.74040576 -7.41116175 -1.53106199 -9.6942431
  1.17119376  9.83533135  2.98442513 -8.20914218]

[ -9.   1.   5.  -8.  -2. -10.   2.  10.   3.  -9.]


In [74]:
#30. How to find common values between two arrays?
Z1 = np.random.randint(-30,30,30)
print(Z1)
print()
Z2 = np.random.randint(-30,30,30)
print(Z2)
print()
print(np.intersect1d(Z1,Z2))

[ -8  12 -14  13  20   5  -1 -24  17 -22  16  15  -6  28 -25   6 -18 -17
  27  21   0 -28  21  10  22 -14 -18   3  17  14]

[ -7  21 -17  -7   2  18  29  22  10   0 -29 -28  18 -25  27 -16   2 -18
   4  21   9 -30 -20  -8 -24 -12  26 -13 -13  -4]

[-28 -25 -24 -18 -17  -8   0  10  21  22  27]


In [77]:
#31. How to ignore all numpy warnings (not recommended)?
defaults = np.seterr(all="ignore")
E = np.ones(1) / 0
print(E)

[inf]


In [78]:
#32. Is the following expressions true?
print(np.sqrt(-1) == np.emath.sqrt(-1))

False


In [80]:
#33. How to get the dates of yesterday, today and tomorrow?

Yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
Today = np.datetime64('today', 'D')
Tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')

print(Yesterday,Today,Tomorrow)

2020-12-02 2020-12-03 2020-12-04
