In [ ]:
# не сделано 7 номеров на 2 звезды.  вместо них сделаны 6 номеров на 3 звезды.

In [5]:
import numpy as np

In [7]:
#34. How to get all the dates corresponding to the month of July 2016?

dates = np.arange('2016-07', '2016-08', dtype='datetime64[D]')

print(dates)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [3]:
#35. How to compute ((A+B)*(-A/2)) in place (without copy)?

A = np.ones(3)*1
B = np.ones(3)*2



np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)

print(np.multiply(A,B,out=A))

[-1.5 -1.5 -1.5]


In [17]:
#36. Extract the integer part of a random array of positive numbers using 4 different methods
D  =   np.random.uniform(4,100,10)
print(D)

print (np.floor(D))

print (np.ceil(D)-1)
print (D - D%1)
print (np.trunc(D))

[77.97794951 60.03706154 10.88192428 20.21928453 28.49322479 75.87671758
 41.82260096 50.07856236 40.35662003 84.65300162]
[77. 60. 10. 20. 28. 75. 41. 50. 40. 84.]
[77. 60. 10. 20. 28. 75. 41. 50. 40. 84.]
[77. 60. 10. 20. 28. 75. 41. 50. 40. 84.]
[77 60 10 20 28 75 41 50 40 84]
[77. 60. 10. 20. 28. 75. 41. 50. 40. 84.]


In [23]:
#37. Create a 5x5 matrix with row values ranging from 0 to 4
V = np.zeros((5,5))

V += np.arange(5)

print(V)


[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [27]:
#38. Consider a generator function that generates 10 integers and use it to build an array
def generator():
    for i in range(1,10):
        yield i

V = np.fromiter(generator(),dtype=int)
print(V)

[1 2 3 4 5 6 7 8 9]


In [37]:
#39. Create a vector of size 10 with values ranging from 0 to 1, both excluded
V = np.linspace(0, 1, num = 12)[1:-1]

print(V)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [40]:
#40. Create a random vector of size 10 and sort it 
v = np.random.random(10)
v.sort()

print(v)

[0.00644825 0.00972662 0.06625594 0.17676362 0.35818159 0.38695335
 0.7039174  0.7412578  0.87305759 0.99349749]


In [46]:
#41. How to sum a small array faster than np.sum?
v = np.random.random(10)

print(np.add.reduce(v))

4.391851158176586


In [61]:
#42. Consider two random array A and B, check if they are equal
A = np.random.randint(0,5,10)
B = np.random.randint(0,5,10)
print(A)
print(B)


print(np.array_equal (A, B))

[2 2 0 0 0 3 1 0 2 2]
[2 3 2 1 1 3 1 4 4 3]
False


In [169]:
#43. Make an array immutable (read-only) 

A = np.random.randint(0,5,10)
A.flags.writeable = False
print(A)
A[0] = 1

[1 3 2 4 4 3 1 0 1 2]


ValueError: assignment destination is read-only

In [65]:
#44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates\
D = np.random.random((10,2))

x,y = D[:,0], D[:,1]

r = np.sqrt(x**2+y**2)

phi = np.arctan2(y,x)

print(r)
print()
print(phi)

[0.88983585 0.8396151  0.88284243 0.85329819 0.68784294 0.81689104
 0.51197347 0.60130021 0.462508   0.9393744 ]

[1.28498901 0.53685854 1.4222169  0.85358869 1.40901328 0.72803716
 0.36528707 0.39240404 0.22475455 0.73719542]


In [69]:
#45. Create random vector of size 10 and replace the maximum value by 0 
v = np.random.random(10)
print(v)

v[v.argmax()] = 0
print(v)

[0.85225204 0.48283132 0.50918418 0.23823909 0.6770697  0.02446185
 0.88120057 0.50811586 0.33742997 0.39537385]
[0.85225204 0.48283132 0.50918418 0.23823909 0.6770697  0.02446185
 0.         0.50811586 0.33742997 0.39537385]


In [70]:
#46. Create a structured array with x and y coordinates covering the [0,1]x[0,1] area
A = np.zeros((5,5), [('X',float),('Y',float)])
X = np.linspace(0,1,5)
Y = np.linspace(0,1,5)
A['X'], A['Y'] = np.meshgrid(X,Y)

print(A)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [76]:
#47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))
X = np.random.random(10)
print(X)

print()

Y = np.random.random(10)
print(Y)

print()

C = 1.0 / np.subtract.outer(X, Y)

print(np.linalg.det(C))

[0.67279354 0.11401192 0.70455543 0.59052398 0.62578387 0.98225402
 0.8449225  0.08577049 0.78525182 0.98863304]

[0.1461394  0.5737147  0.27277317 0.94788624 0.66686578 0.95906102
 0.00110777 0.01653793 0.08106802 0.94495607]

56824.29931330357


In [81]:
#48. Print the minimum and maximum representable value for each numpy scalar type

for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)


for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [84]:
#49. How to print all the values of an array?
X = np.random.random(49)
print(X)

[0.34227453 0.28190605 0.19627134 0.5824777  0.64021444 0.70534957
 0.19035432 0.18110646 0.04493389 0.45945144 0.90709353 0.95704457
 0.92331969 0.06476996 0.81473366 0.64628681 0.18518473 0.38571778
 0.64640265 0.10755483 0.18665834 0.67298985 0.02355814 0.49004294
 0.29976883 0.09425414 0.46609602 0.16822659 0.77453933 0.48221753
 0.05900434 0.95154861 0.75509576 0.83366526 0.13718336 0.90030565
 0.67994308 0.11270854 0.4129007  0.06275988 0.2921606  0.90368449
 0.45752206 0.07794166 0.95779097 0.33703908 0.03911848 0.20764326
 0.91711033]


In [92]:
#50. How to find the closest value (to a given scalar) in a vector?
X = np.arange(50)
print(X)
v = np.random.uniform(0,49)
print(v)
i = (np.abs(X-v)).argmin()

print(X[i])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
37.01793674839624
37


In [ ]:
#51. Create a structured array representing a position (x,y) and a color (r,g,b)
#-

In [170]:
#52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances
#-

In [168]:
#53. How to convert a float (32 bits) array into an integer (32 bits) in place?
M = np.arange(53, dtype=np.int32)
print(M)
print()
M = M.astype(np.float32, copy=False)

print(M)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52]

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35.
 36. 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49. 50. 51. 52.]


In [ ]:
#54. How to read the following file?
#-

In [ ]:
#55. What is the equivalent of enumerate for numpy arrays?
#-

In [163]:
#56. Generate a generic 2D Gaussian-like array
x,y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))

D = np.sqrt(x**2+y**2)

mu = 5
s = 10

Gaussian = np.exp(- ( (D-mu)**2 / ( 2 * s**2 ) ) )
print(Gaussian)



[[0.93773365 0.93269073 0.92835111 0.92510232 0.92334343 0.92334343
  0.92510232 0.92835111 0.93269073 0.93773365]
 [0.93269073 0.92676784 0.92147724 0.91734615 0.91502608 0.91502608
  0.91734615 0.92147724 0.92676784 0.93269073]
 [0.92835111 0.92147724 0.91502608 0.90964161 0.90639775 0.90639775
  0.90964161 0.91502608 0.92147724 0.92835111]
 [0.92510232 0.91734615 0.90964161 0.90254125 0.89758355 0.89758355
  0.90254125 0.90964161 0.91734615 0.92510232]
 [0.92334343 0.91502608 0.90639775 0.89758355 0.88934796 0.88934796
  0.89758355 0.90639775 0.91502608 0.92334343]
 [0.92334343 0.91502608 0.90639775 0.89758355 0.88934796 0.88934796
  0.89758355 0.90639775 0.91502608 0.92334343]
 [0.92510232 0.91734615 0.90964161 0.90254125 0.89758355 0.89758355
  0.90254125 0.90964161 0.91734615 0.92510232]
 [0.92835111 0.92147724 0.91502608 0.90964161 0.90639775 0.90639775
  0.90964161 0.91502608 0.92147724 0.92835111]
 [0.93269073 0.92676784 0.92147724 0.91734615 0.91502608 0.91502608
  0.91734615

In [159]:
#57. How to randomly place p elements in a 2D array?

M = np.zeros((10,10))
p = 10
np.put(M, np.random.choice(range(10*10), p),57)

print(M)

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. 57.  0.  0.  0.  0. 57.  0.  0.]
 [ 0.  0.  0.  0.  0.  0. 57.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [57.  0.  0. 57.  0.  0.  0.  0. 57.  0.]
 [ 0.  0.  0.  0.  0. 57.  0.  0.  0.  0.]
 [ 0. 57.  0.  0.  0. 57.  0.  0.  0. 57.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]


In [154]:
#58. Subtract the mean of each row of a matrix
#-

In [151]:
#59. How to sort an array by the nth column? 
M = np.random.randint(0,100,(10,10))

print(M)
print()
k=5
print(M[M[:,k].argsort()])

[[25 40 52 92 26 53 53 97 97 34]
 [63 23  4 23 27 76 75  2 31 89]
 [26  7 34 97 48 82 49 74 35 80]
 [11 19 67 83 81 77 30 37 73 40]
 [99 82 18 64 76 18 87 64 54 66]
 [18 26 16  3 25 43 79 28 48 24]
 [30 71 78 45 40 21 24 40 10 49]
 [50 79 85 22 70 71 96 28 83 76]
 [79 54 50 81 64  1 31 16 26  2]
 [ 5 37 22 77 15 27 17 15 28 95]]

[[79 54 50 81 64  1 31 16 26  2]
 [99 82 18 64 76 18 87 64 54 66]
 [30 71 78 45 40 21 24 40 10 49]
 [ 5 37 22 77 15 27 17 15 28 95]
 [18 26 16  3 25 43 79 28 48 24]
 [25 40 52 92 26 53 53 97 97 34]
 [50 79 85 22 70 71 96 28 83 76]
 [63 23  4 23 27 76 75  2 31 89]
 [11 19 67 83 81 77 30 37 73 40]
 [26  7 34 97 48 82 49 74 35 80]]


In [146]:
#60. How to tell if a given 2D array has null columns?
M = np.random.randint(0,4,(2,30))
print(M)
print((~M.any(axis=0)).any())

[[1 0 3 2 3 3 2 2 0 2 3 0 2 3 1 2 3 0 2 0 3 2 1 1 2 1 2 2 0 2]
 [2 1 2 2 1 2 1 2 1 3 2 0 1 3 3 1 2 1 2 0 1 1 0 1 0 3 1 1 1 3]]
True


In [134]:
#61. Find the nearest value from a given value in an array
M = np.random.randint(0, 100, (5, 5))
print(Z)

m = 61.2

x = M.flat[np.abs(M - z).argmin()]

print(x)



[[0 1 1 1 1 2 1 2 1 1]
 [1 2 2 2 0 1 2 1 2 1]
 [2 1 0 1 0 0 2 1 0 0]]
65


In [131]:
#62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? 
# -

In [120]:
#63. Create an array class that has a name attribute
# -

SyntaxError: invalid syntax (<ipython-input-120-185ad5095d1d>, line 2)

In [209]:
#70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)
x = [1,2,3,4,5]
v = [1,0,0,0,2,0,0,0,3,0,0,0,4,0,0,0,5]


print(v)

[1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5]


In [115]:
#71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

B = 5*np.ones((5,5))

print(A * B[:,:,None])

[[[10. 10. 10.]
  [10. 10. 10.]
  [10. 10. 10.]
  [10. 10. 10.]
  [10. 10. 10.]]

 [[10. 10. 10.]
  [10. 10. 10.]
  [10. 10. 10.]
  [10. 10. 10.]
  [10. 10. 10.]]

 [[10. 10. 10.]
  [10. 10. 10.]
  [10. 10. 10.]
  [10. 10. 10.]
  [10. 10. 10.]]

 [[10. 10. 10.]
  [10. 10. 10.]
  [10. 10. 10.]
  [10. 10. 10.]
  [10. 10. 10.]]

 [[10. 10. 10.]
  [10. 10. 10.]
  [10. 10. 10.]
  [10. 10. 10.]
  [10. 10. 10.]]]


In [104]:
#72. How to swap two rows of an array? (★★★)

M = np.random.randint(0, 100, (10, 10))
print(M)
print()
M[[0,1]] = M[[1,0]]

print(M)

[[10 76  0 80 47 57 15 73 14  4]
 [11 54 15 86 36 45 71 32 44 12]
 [84 48 95 93 27 70 35 97 35 81]
 [ 6 88  3 37 54 64 20 98 50 74]
 [ 4 93 71 49 78 68 60  7 63 56]
 [81 56 89 90 40 74 70 71 95  1]
 [41 11  7 20 38  6 11 55 35 64]
 [ 8 29 59  6 44 11 65 64 75 29]
 [12 74 31 18 65 49 42 19 44 14]
 [55 65 16 44 11 19 19 52 58  2]]

[[11 54 15 86 36 45 71 32 44 12]
 [10 76  0 80 47 57 15 73 14  4]
 [84 48 95 93 27 70 35 97 35 81]
 [ 6 88  3 37 54 64 20 98 50 74]
 [ 4 93 71 49 78 68 60  7 63 56]
 [81 56 89 90 40 74 70 71 95  1]
 [41 11  7 20 38  6 11 55 35 64]
 [ 8 29 59  6 44 11 65 64 75 29]
 [12 74 31 18 65 49 42 19 44 14]
 [55 65 16 44 11 19 19 52 58  2]]


In [119]:
#74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)
x = [0, 1, 1, 2, 2, 2, 3, 3, 3, 3]
C = np.bincount(x)
print(C)
print()
A = np.repeat(np.arange(len(C)), C)

print(A)
print(np.bincount(A))

[1 2 3 4]

[0 1 1 2 2 2 3 3 3 3]
[1 2 3 4]


In [205]:
#82. Compute a matrix rank(★★★)

M = np.random.randint(0, 2, (10, 10))
print(M)
print(np.linalg.matrix_rank(M))

U, S, V = np.linalg.svd(M) 
r = np.sum(S > 1e-820)

print(r)


[[1 1 1 1 0 1 0 0 0 0]
 [1 0 1 1 1 1 0 0 0 1]
 [1 0 0 0 1 0 1 1 1 1]
 [1 0 0 1 0 1 0 0 1 0]
 [0 1 1 0 0 0 1 0 1 0]
 [0 0 1 0 1 1 1 1 1 1]
 [1 0 1 0 0 1 1 0 0 1]
 [0 1 0 0 0 1 0 0 1 1]
 [0 1 1 0 0 1 1 1 0 1]
 [0 0 1 0 0 0 1 1 0 1]]
10
10


In [207]:
#83. How to find the most frequent value in an array?(★★★)
M = np.random.randint(0,83,83)
print(M)

print(np.bincount(M).argmax())

[19 43 43 70  5 28 44  7 43 13 25 24 79 46 13 75 20 56 12 16 39 74 49 15
 55 54  9 44 16 18 82  6 16 37 78 34 60 58 25 32 58 33 41 39 23 49 35 78
 44 22 72 28  1 69 20 75 44 67 75 39 15  5 77 60 73 82 59 30 73 62 15 49
  1 65  4 40 44 32 17 30 35 51 11]
44
